version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: bouncehouse-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: bouncehousekids
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d:ro
    networks:
      - bouncehouse-network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bouncehouse-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/bouncehousekids?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - mongodb
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - bouncehouse-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: bouncehouse-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_STRIPE_PUBLIC_KEY=${REACT_APP_STRIPE_PUBLIC_KEY}
      - REACT_APP_APP_NAME=${REACT_APP_APP_NAME}
      - REACT_APP_COMPANY_NAME=${REACT_APP_COMPANY_NAME}
      - REACT_APP_COMPANY_EMAIL=${REACT_APP_COMPANY_EMAIL}
      - REACT_APP_COMPANY_PHONE=${REACT_APP_COMPANY_PHONE}
    depends_on:
      - server
    networks:
      - bouncehouse-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: bouncehouse-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - client
      - server
    networks:
      - bouncehouse-network

volumes:
  mongodb_data:

networks:
  bouncehouse-network:
    driver: bridge